### ISSUE TITLE
Working SSL/https

### ISSUE THREAD

**Issue by doctaweeks** [rpm-software-management/rpm-web#5] opened 2017-11-16 21:29 UTC
Current certs do not cover domains rpm.org or ftp.rpm.org.

**Comment by saper** [comment] 2023-07-14 22:55
https://rpm.org works better in July 2023, but https://ftp.rpm.org is there with an osuosl.org certificate.

Since the certificate is issued for osuosl.org and the wildcard name *.osuosl.org and I guess they are using ACME protocol to automatically renew their certificates. Wildcard names shall only be requested using the DNS challenge, which requires write access to the DNS hosting service - not sure if they could be given write access to the `rpm.org` zone to fix this issue? 

Or maybe a `_acme_challenge.ftp.rpm.org. IN CNAME _acme_challenge.osuosl.org.` or something like that could be added to make it work somehow.

**Comment by ffesti** [comment] 2024-03-27 07:57
#47 is a duplicate of this. But as I already commented there I'll close this even if it is the older one.

**Closed as completed by ffesti** 2024-03-27 07:57 UTC
